version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    groups:
      dev-tools-minor-patch:
        dependency-type: development
        patterns:
          - "eslint"
          - "@typescript-eslint/*"
          - "typescript"
          - "wrangler"
          - "husky"
          - "@types/*"
          - "@cloudflare/workers-types"
        update-types:
          - minor
          - patch
      prod-minor-patch:
        dependency-type: production
        update-types:
          - minor
          - patch

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    groups:
      actions-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
