name = "rss-summary-dev"
main = "src/index.ts"
compatibility_date = "2024-09-25"
node_compat = true

# 開発環境（デフォルト）
[[d1_databases]]
binding = "DB"
database_name = "rss-summary-dev-db"
database_id = "bc59f74a-24a6-4600-9f50-34c387892898"
migrations_dir = "migrations"

[vars]
ENVIRONMENT = "development"
DISCORD_WEBHOOK_URL = "https://discord.com/api/webhooks/1389251072148770866/dImIVp_IEDP4dj6PmR5hddPq2dMRuJiqENPMn0iN3P3_le6pL1dJk5k7HUVQUJc9inh-"

# 本番環境
[env.production]
name = "rss-summary"

[[env.production.d1_databases]]
binding = "DB"
database_name = "rss-summary-prod-db"
database_id = "aa1bfa7d-0045-4848-93ec-78cd099c951b"
migrations_dir = "migrations"

[env.production.vars]
ENVIRONMENT = "production"
DISCORD_WEBHOOK_URL = "https://discord.com/api/webhooks/1389251072148770866/dImIVp_IEDP4dj6PmR5hddPq2dMRuJiqENPMn0iN3P3_le6pL1dJk5k7HUVQUJc9inh-"

[env.production.triggers]
crons = ["30 6 * * *"]