name = "rss-summary"
main = "src/index.ts"
compatibility_date = "2024-09-25"
node_compat = true

[env.production]
name = "rss-summary"

[env.development]
name = "rss-summary-dev"

[[d1_databases]]
binding = "DB"
database_name = "rss-summary-db"
database_id = ""
migrations_dir = "migrations"

[triggers]
crons = ["30 6 * * *"]

[vars]
ENVIRONMENT = "development"