name = "rss-summary-dev"
main = "src/index.ts"
compatibility_date = "2024-09-25"
node_compat = true

# 開発環境（デフォルト）
[[d1_databases]]
binding = "DB"
database_name = "rss-summary-dev-db"
database_id = "bc59f74a-24a6-4600-9f50-34c387892898"
migrations_dir = "migrations"

[vars]
ENVIRONMENT = "development"

# 本番環境
[env.production]
name = "rss-summary"

[[env.production.d1_databases]]
binding = "DB"
database_name = "rss-summary-prod-db"
database_id = "aa1bfa7d-0045-4848-93ec-78cd099c951b"
migrations_dir = "migrations"

[env.production.vars]
ENVIRONMENT = "production"

[env.production.triggers]
crons = ["30 6 * * *"]